/*************************************************
** SCHEMA(S)
*************************************************/
CREATE SCHEMA BLUEWALLET;


/*************************************************
** TABLES
*************************************************/

-- TB_USUARIO
CREATE TABLE BLUEWALLET.TB_USUARIO (
    ID INTEGER NOT NULL,
    NOME CHAR(50) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
	CELULAR VARCHAR(13),
    EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	GOOGLE_CODE VARCHAR(255),
	
    CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID)
);

-- TB_CATEGORIA_RECEITA
CREATE TABLE BLUEWALLET.TB_CATEGORIA_RECEITA (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    FLG_ATIVO BOOLEAN NOT NULL,
	
    CONSTRAINT PK_ID_CATEGORIA_RECEITA PRIMARY KEY (ID)
);

-- TB_CATEGORIA_DESPESA
CREATE TABLE BLUEWALLET.TB_CATEGORIA_DESPESA (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    FLG_ATIVO BOOLEAN NOT NULL,
	
    CONSTRAINT PK_ID_DESPESA PRIMARY KEY (ID)
);