/*************************************************
** SCHEMA(S)
*************************************************/
CREATE SCHEMA BLUEWALLET;


/*************************************************
** TABLES
*************************************************/

-- TB_USUARIO
CREATE TABLE BLUEWALLET.TB_USUARIO (
    ID INTEGER NOT NULL,
    NOME CHAR(50) NOT NULL,
    SOBRENOME VARCHAR(50) NOT NULL,
	CELULAR VARCHAR(13),
    EMAIL VARCHAR(100) NOT NULL,
	SENHA VARCHAR(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	GOOGLE_CODE VARCHAR(255),
	
    CONSTRAINT PK_ID_USUARIO PRIMARY KEY (ID)
);

-- TB_CATEGORIA_RECEITA
CREATE TABLE BLUEWALLET.TB_CATEGORIA_RECEITA (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    FLG_ATIVO BOOLEAN NOT NULL,
	
    CONSTRAINT PK_ID_CATEGORIA_RECEITA PRIMARY KEY (ID)
);

-- TB_CATEGORIA_DESPESA
CREATE TABLE BLUEWALLET.TB_CATEGORIA_DESPESA (
    ID INTEGER NOT NULL,
    DESCRICAO VARCHAR(30) NOT NULL,
    FLG_ATIVO BOOLEAN NOT NULL,
	
    CONSTRAINT PK_ID_DESPESA PRIMARY KEY (ID)
);

-- TB_LANCAMENTO_RECEITA
create table BLUEWALLET.TB_LANCAMENTO_RECEITA (
	ID INTEGER NOT NULL,
	USUARIO_ID INTEGER NOT NULL,
	CATEGORIA_RECEITA_ID INTEGER NOT NULL,
	DESCRICAO VARCHAR(50),
	NUMERO_PARCELAS INTEGER,
	VALOR FLOAT not null,
	DATA_LANCAMENTO DATE,
	FLG_PAGAMENTO_EFETUADO BOOLEAN NOT NULL,
	
	CONSTRAINT PK_ID_LANCAMENTO_RECEITA PRIMARY KEY (ID),
	constraint FK_USUARIO_ID_USUARIO foreign key (USUARIO_ID) references BLUEWALLET.TB_USUARIO(ID),
	constraint FK_CATEGORIA_RECEITA_ID foreign key (CATEGORIA_RECEITA_ID) references BLUEWALLET.TB_CATEGORIA_RECEITA(ID)
);

-- TB_LANCAMENTO_RECEITA
create table BLUEWALLET.TB_LANCAMENTO_DESPESA (
	ID INTEGER NOT NULL,
	USUARIO_ID INTEGER NOT NULL,
	CATEGORIA_DESPESA_ID INTEGER NOT NULL,
	DESCRICAO VARCHAR(50),
	NUMERO_PARCELAS INTEGER,
	VALOR FLOAT not null,
	DATA_PAGAMENTO DATE,
	FLG_PAGO BOOLEAN NOT NULL,
	
	CONSTRAINT PK_ID_LANCAMENTO_DESPESA PRIMARY KEY (ID),
	constraint FK_USUARIO_ID_USUARIO foreign key (USUARIO_ID) references BLUEWALLET.TB_USUARIO(ID),
	constraint FK_CATEGORIA_RECEITA_ID foreign key (CATEGORIA_RECEITA_ID) references BLUEWALLET.TB_CATEGORIA_RECEITA(ID)
);